# Generated by Django 5.2.14 on 2026-05-12 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('intro_text', models.TextField(blank=True, help_text='Introduction text for the collection')),
                ('conclusion_text', models.TextField(blank=True, help_text='Conclusion text for the collection')),
                ('is_published', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='editorial/collections/')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('description', models.TextField(blank=True, help_text='Why this app is included in the collection')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.app')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.collection')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('collection', 'app')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='apps',
            field=models.ManyToManyField(related_name='collections', through='editorial.CollectionApp', to='catalog.app'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('excerpt', models.TextField(help_text='Brief summary for social media and search results', max_length=500)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('article', 'Article'), ('guide', 'How-to Guide'), ('comparison', 'Comparison'), ('roundup', 'App Roundup'), ('news', 'News')], default='article', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, help_text='Keep featured on homepage until this date', null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='editorial/covers/')),
                ('cover_alt_text', models.CharField(blank=True, max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('reading_time_minutes', models.PositiveSmallIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('note', models.CharField(blank=True, help_text='Editorial note about this app in the context of the post', max_length=300)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.app')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.post')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('post', 'app')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='related_apps',
            field=models.ManyToManyField(blank=True, related_name='editorial_posts', through='editorial.PostApp', to='catalog.app'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='editorial.tag'),
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('introduction', models.TextField()),
                ('conclusion', models.TextField()),
                ('criteria', models.JSONField(default=dict, help_text='Comparison criteria and scores in JSON format')),
                ('is_published', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
                ('primary_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_primary', to='catalog.app')),
                ('secondary_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_secondary', to='catalog.app')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('primary_app', 'secondary_app'), name='unique_comparison_pair')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='editorial_p_status_5ce1be_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-published_at'], name='editorial_p_publish_4b1397_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-published_at'], name='editorial_p_post_ty_5b846f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['featured_until'], name='editorial_p_feature_9ee7b2_idx'),
        ),
    ]
