# Generated by Django 5.2.14 on 2026-05-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant_name', models.CharField(max_length=200)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('verification_method', models.CharField(help_text='How they proved ownership (email, repo access, etc.)', max_length=100)),
                ('evidence', models.TextField(help_text='Evidence of ownership (screenshots, emails, etc.)')),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitter_ip', models.GenericIPAddressField()),
                ('turnstile_token', models.CharField(blank=True, max_length=2000)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='catalog.app')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'status'], name='submissions_app_id_4214ee_idx'), models.Index(fields=['status', '-created_at'], name='submissions_status_d7fb24_idx'), models.Index(fields=['claimant_email'], name='submissions_claiman_878512_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('app', 'claimant_email'), name='unique_claim_per_app_email')],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=280)),
                ('long_description', models.TextField(blank=True)),
                ('developer_name', models.CharField(blank=True, max_length=200)),
                ('developer_email', models.EmailField(max_length=254)),
                ('official_url', models.URLField()),
                ('install_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('suggested_platforms', models.CharField(help_text='Comma-separated list of platforms (ChatGPT, Claude, etc.)', max_length=300)),
                ('suggested_categories', models.CharField(help_text='Comma-separated list of categories', max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to app')], default='pending', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitter_ip', models.GenericIPAddressField()),
                ('turnstile_token', models.CharField(blank=True, max_length=2000)),
                ('created_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='catalog.app')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='submissions_status_fa968c_idx'), models.Index(fields=['developer_email'], name='submissions_develop_0cfde5_idx'), models.Index(fields=['-created_at'], name='submissions_created_be6fdb_idx')],
            },
        ),
    ]
