# Generated by Django 5.2.14 on 2026-05-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claimrequest',
            name='auto_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='auto_check_log',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='auto_check_status',
            field=models.CharField(choices=[('pending', 'Auto-check pending'), ('passed', 'Auto-check passed'), ('failed', 'Auto-check failed'), ('skipped', 'Auto-check skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who made the final decision', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
