# Generated by Django 5.2.14 on 2026-05-13 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text="Logical source identifier — typically the source_type used by apps.sources (e.g. 'mcp_registry'), or a discovery source (e.g. 'rss', 'github_mcp').", max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dry_run', 'Dry-run (no DB writes)')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('beat', 'Celery beat'), ('manual', 'Manual command'), ('admin', 'Admin action')], default='manual', max_length=20)),
                ('triggered_by', models.CharField(blank=True, help_text='Username or beat-task slug; informational, not auth.', max_length=120)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, help_text="Sum of LLMCallLog.cost_usd across this run's tasks.", max_digits=10)),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Free-form counters: drafts_enriched, capabilities_added, etc.')),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='agent_agent_started_a632b8_idx'), models.Index(fields=['status', '-started_at'], name='agent_agent_status_5e0efa_idx'), models.Index(fields=['source_type', '-started_at'], name='agent_agent_source__312c72_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching source'), ('enriching', 'Calling LLM'), ('validating', 'Validating LLM output'), ('persisted', 'Persisted to DB'), ('dry_run', 'Dry-run (not persisted)'), ('failed', 'Failed'), ('skipped', 'Skipped (e.g. dedup)')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('diff_summary', models.JSONField(blank=True, default=dict, help_text='Snapshot of what the agent proposed vs the previous state. Persisted for both real and dry-run modes — auditable trace of every LLM decision the editor will see.')),
                ('app', models.ForeignKey(blank=True, help_text='Nullable: discovery tasks operate on a URL before any App is created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrichment_tasks', to='catalog.app')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agent.agentrun')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('prompt_version', models.CharField(blank=True, help_text="Versioned prompt key — e.g. 'enrich-v1.0'.", max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_tokens', models.PositiveIntegerField(default=0, help_text='Tokens served from prompt cache (Anthropic). 0 for OpenAI / mock.')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Per-call cost computed from provider pricing at request time.', max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False, help_text='True when the call was served by MockLLMProvider in tests / dry-run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='agent.enrichmenttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedsReviewQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('enriched', 'Enrichment proposal'), ('reactualized', 'Re-actualization diff'), ('vanished', 'Source vanished')], max_length=20)),
                ('payload', models.JSONField(help_text='Structured proposal — keys mirror EnrichedDraft fields. Each entry typically carries evidence_map and confidence values so the editor sees WHY the agent proposed the change.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_queue_entries', to='catalog.app')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_queue_resolutions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_entries', to='agent.enrichmenttask')),
            ],
            options={
                'verbose_name_plural': 'Needs-review queue entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='enrichmenttask',
            index=models.Index(fields=['run', 'status'], name='agent_enric_run_id_2be7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichmenttask',
            index=models.Index(fields=['app', '-started_at'], name='agent_enric_app_id_a1600b_idx'),
        ),
        migrations.AddIndex(
            model_name='enrichmenttask',
            index=models.Index(fields=['-started_at'], name='agent_enric_started_7c5621_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['task', 'created_at'], name='agent_llmca_task_id_db9dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['-created_at'], name='agent_llmca_created_dec935_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcalllog',
            index=models.Index(fields=['provider', 'model'], name='agent_llmca_provide_2ebbcf_idx'),
        ),
        migrations.AddIndex(
            model_name='needsreviewqueueentry',
            index=models.Index(fields=['app', '-created_at'], name='agent_needs_app_id_dacbe3_idx'),
        ),
        migrations.AddIndex(
            model_name='needsreviewqueueentry',
            index=models.Index(fields=['kind', 'resolved_at'], name='agent_needs_kind_9cbcfa_idx'),
        ),
        migrations.AddIndex(
            model_name='needsreviewqueueentry',
            index=models.Index(fields=['-created_at'], name='agent_needs_created_02f3a1_idx'),
        ),
    ]
