# Generated by Django 5.2.14 on 2026-05-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_needsreviewqueueentry_review_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmcalllog',
            name='cached_tokens',
            field=models.PositiveIntegerField(default=0, help_text='Tokens served from prompt cache (OpenAI prompt cache or Anthropic cache_read). Subtracted from billable input before the cached-input price is applied. 0 for mock provider.'),
        ),
    ]
