# Generated by Django 5.2.14 on 2026-05-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_alter_llmcalllog_cached_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMonthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the UTC calendar month this row tracks.', unique=True)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Sum of LLMCallLog.cost_usd written this month.', max_digits=12)),
                ('budget_usd', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of AGENT_MONTHLY_BUDGET_USD when the row was last updated.', max_digits=10)),
                ('discovery_disabled_at', models.DateTimeField(blank=True, help_text='Set when monthly cost first crossed 80% of the budget.', null=True)),
                ('hard_stop_at', models.DateTimeField(blank=True, help_text='Set when monthly cost first crossed 100% of the budget.', null=True)),
                ('notified_80_at', models.DateTimeField(blank=True, null=True)),
                ('notified_100_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
    ]
