# Generated by Django 5.2.14 on 2026-05-12 15:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', '-search_count', 'query'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=500)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.PositiveIntegerField()),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='search_sear_created_4a70e7_idx'), models.Index(fields=['query'], name='search_sear_query_465835_idx'), django.contrib.postgres.indexes.GinIndex(fields=['query'], name='search_log_query_trgm_gin', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
