# Generated by Django 5.2.14 on 2026-05-12 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnparsedRegistryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('error', models.TextField(blank=True)),
                ('schema_version', models.CharField(blank=True, max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-received_at'], name='sources_unp_receive_9ea408_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('official', 'Official page'), ('install', 'Install URL'), ('directory', 'Platform directory URL'), ('repo', 'Repository URL')], max_length=20)),
                ('url', models.URLField()),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ok', models.BooleanField()),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_checks', to='catalog.app')),
            ],
            options={
                'indexes': [models.Index(fields=['app', 'target', '-checked_at'], name='sources_lin_app_id_233341_idx'), models.Index(fields=['-checked_at'], name='sources_lin_checked_dbefe7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('official', 'Official page'), ('install', 'Install URL'), ('directory', 'Platform directory URL'), ('repo', 'Repository URL')], max_length=20)),
                ('url', models.URLField()),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_health', to='catalog.app')),
            ],
            options={
                'indexes': [models.Index(fields=['-consecutive_failures'], name='sources_lin_consecu_c75a22_idx')],
                'unique_together': {('app', 'target')},
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('mcp_registry', 'MCP Registry'), ('submission', 'User submission'), ('chatgpt_directory', 'ChatGPT App Directory'), ('claude_connectors', 'Claude Connectors')], max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Set to false when the source no longer references this app (e.g. server vanished from MCP Registry).')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='catalog.app')),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'external_id'], name='sources_sou_source__6c69c0_idx'), models.Index(fields=['app', 'source_type'], name='sources_sou_app_id_8275c4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source_type', 'external_id'), name='source_dedupe_by_external_id')],
            },
        ),
    ]
