# Generated by Django 5.2.14 on 2026-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_backfill_mcp_appplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('mcp_registry', 'MCP Registry'), ('submission', 'User submission'), ('chatgpt_directory', 'ChatGPT App Directory'), ('claude_connectors', 'Claude Connectors'), ('agent_enrich', 'Agent enrichment')], max_length=40),
        ),
    ]
