# Generated by Django 5.2.14 on 2026-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_path', models.CharField(max_length=500, unique=True)),
                ('to_path', models.CharField(max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['from_path'], name='seo_redirec_from_pa_bc2deb_idx'), models.Index(fields=['is_active'], name='seo_redirec_is_acti_475288_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('home', 'Home Page'), ('search', 'Search Page'), ('category', 'Category Page'), ('platform', 'Platform Page'), ('blog', 'Blog Index')], max_length=50)),
                ('page_identifier', models.CharField(blank=True, help_text='Slug or identifier for specific page (e.g. category slug)', max_length=200)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/')),
                ('twitter_title', models.CharField(blank=True, max_length=200)),
                ('twitter_description', models.CharField(blank=True, max_length=300)),
                ('json_ld', models.JSONField(blank=True, default=dict, help_text='Additional structured data in JSON-LD format')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['page_type', 'page_identifier'], name='seo_seopage_page_ty_b14df3_idx')],
                'unique_together': {('page_type', 'page_identifier')},
            },
        ),
    ]
