from __future__ import annotations

import json
from decimal import Decimal
from io import StringIO

import pytest
from django.core.management import call_command

from apps.agent.models import AgentRun, EnrichmentTask, LLMCallLog
from apps.agent.reports import phase3_gate_report
from apps.catalog.models import App
from apps.sources.models import Source

pytestmark = pytest.mark.django_db


def _app(slug: str, status: str = App.AppStatus.DRAFT) -> App:
    return App.objects.create(
        name=slug.replace("-", " ").title(),
        slug=slug,
        short_description="Generated by Phase 3.",
        status=status,
    )


def _phase3_source(app: App, source_type: str) -> Source:
    return Source.objects.create(
        app=app,
        source_type=source_type,
        source_url=f"https://example.test/{app.slug}",
        external_id=f"{source_type}:{app.slug}",
        payload={"agent_enrichment": {"name": app.name}},
    )


def _llm_cost(app: App, source_type: str, cost: Decimal, *, is_mock=False) -> None:
    run = AgentRun.objects.create(
        source_type=source_type,
        status=AgentRun.Status.SUCCEEDED,
    )
    task = EnrichmentTask.objects.create(
        run=run,
        app=app,
        source_url=f"https://example.test/{app.slug}",
        status=EnrichmentTask.Status.PERSISTED,
    )
    LLMCallLog.objects.create(
        task=task,
        provider="mock" if is_mock else "openai",
        model="test-model",
        prompt_version="enrich-new-v1.0",
        input_tokens=100,
        output_tokens=40,
        cost_usd=cost,
        is_mock=is_mock,
    )


def test_phase3_gate_report_counts_generated_apps_and_cost() -> None:
    draft_app = _app("draft-from-rss")
    published_app = _app("published-from-github", App.AppStatus.PUBLISHED)
    ignored_app = _app("manual-app", App.AppStatus.PUBLISHED)
    _phase3_source(draft_app, Source.SourceType.RSS_DISCOVERY)
    _phase3_source(published_app, Source.SourceType.GITHUB_MCP)
    Source.objects.create(
        app=ignored_app,
        source_type=Source.SourceType.MANUAL,
        payload={"agent_enrichment": {"name": ignored_app.name}},
    )
    _llm_cost(draft_app, Source.SourceType.RSS_DISCOVERY, Decimal("0.020000"))
    _llm_cost(
        published_app,
        Source.SourceType.GITHUB_MCP,
        Decimal("0.030000"),
        is_mock=True,
    )

    report = phase3_gate_report()

    assert report.generated_apps == 2
    assert report.draft_apps == 1
    assert report.published_apps == 1
    assert report.approval_rate == Decimal("50.0")
    assert report.total_cost_usd == Decimal("0.050000")
    assert report.cost_per_published_usd == Decimal("0.050000")
    assert report.llm_calls == 2
    assert report.mock_llm_calls == 1
    assert report.real_llm_calls == 1
    assert report.cost_basis_complete is False
    assert report.gate_open is False


def test_phase3_report_command_json_output() -> None:
    app = _app("published-from-rss", App.AppStatus.PUBLISHED)
    _phase3_source(app, Source.SourceType.RSS_DISCOVERY)
    _llm_cost(app, Source.SourceType.RSS_DISCOVERY, Decimal("0.012345"))
    out = StringIO()

    call_command("agent_phase3_report", "--json", stdout=out)

    payload = json.loads(out.getvalue())
    assert payload["generated_apps"] == 1
    assert payload["published_apps"] == 1
    assert payload["approval_rate"] == "100.0"
    assert payload["cost_per_published_usd"] == "0.012345"
    assert payload["cost_basis_complete"] is True
    assert payload["gate_open"] is False
