# Generated by Django 5.2.14 on 2026-05-12 15:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subject_line', models.CharField(max_length=200)),
                ('preheader', models.CharField(blank=True, help_text='Preview text shown in email clients', max_length=150)),
                ('intro_text', models.TextField(blank=True)),
                ('conclusion_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('clicked_count', models.PositiveIntegerField(default=0)),
                ('bounced_count', models.PositiveIntegerField(default=0)),
                ('unsubscribed_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('description', models.TextField(help_text='Editorial description of why this app is featured')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.app')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.issue')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('issue', 'app')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='featured_apps',
            field=models.ManyToManyField(blank=True, related_name='newsletter_issues', through='newsletter.IssueApp', to='catalog.app'),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Email bounced')], default='pending', max_length=20)),
                ('confirmation_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], default='weekly', max_length=20)),
                ('source', models.CharField(blank=True, help_text='How they found us (home page, blog post, etc.)', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('total_opens', models.PositiveIntegerField(default=0)),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-created_at'], name='newsletter__status_9ac9df_idx'), models.Index(fields=['email'], name='newsletter__email_c1e80c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_opens', to='newsletter.issue')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_opens', to='newsletter.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='EmailClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('app', 'App link'), ('blog', 'Blog post link'), ('website', 'Website link'), ('unsubscribe', 'Unsubscribe link')], max_length=20)),
                ('target_url', models.URLField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('app', models.ForeignKey(blank=True, help_text='App that was clicked (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.app')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_clicks', to='newsletter.issue')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_clicks', to='newsletter.subscriber')),
            ],
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', '-created_at'], name='newsletter__status_a634c2_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['-sent_at'], name='newsletter__sent_at_73a4c8_idx'),
        ),
        migrations.AddIndex(
            model_name='emailopen',
            index=models.Index(fields=['issue', '-created_at'], name='newsletter__issue_i_f864d3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailopen',
            index=models.Index(fields=['subscriber', '-created_at'], name='newsletter__subscri_9d0a78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailopen',
            unique_together={('issue', 'subscriber')},
        ),
        migrations.AddIndex(
            model_name='emailclick',
            index=models.Index(fields=['issue', '-created_at'], name='newsletter__issue_i_7a14fb_idx'),
        ),
        migrations.AddIndex(
            model_name='emailclick',
            index=models.Index(fields=['subscriber', '-created_at'], name='newsletter__subscri_efc9cb_idx'),
        ),
    ]
