# Generated by Django 5.2.14 on 2026-05-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('home', 'Home page'), ('search', 'Search results'), ('app_detail', 'App detail'), ('category', 'Category page'), ('platform', 'Platform page')], max_length=20)),
                ('page_identifier', models.CharField(blank=True, max_length=200)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('load_time_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['page_type', '-created_at'], name='analytics_p_page_ty_633dcc_idx'), models.Index(fields=['-created_at'], name='analytics_p_created_44ec6b_idx'), models.Index(fields=['page_identifier', '-created_at'], name='analytics_p_page_id_6c3a4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link_type', models.CharField(choices=[('official', 'Official page'), ('install', 'Install URL'), ('repo', 'Repository'), ('platform', 'Platform directory')], default='official', max_length=20)),
                ('source_page', models.CharField(blank=True, help_text='Where the click originated (home, search, detail, etc.)', max_length=100)),
                ('source_position', models.PositiveSmallIntegerField(blank=True, help_text='Position in list/grid (for ranking analysis)', null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='catalog.app')),
            ],
            options={
                'indexes': [models.Index(fields=['app', '-created_at'], name='analytics_c_app_id_5aa4d8_idx'), models.Index(fields=['-created_at'], name='analytics_c_created_c54993_idx'), models.Index(fields=['source_page', '-created_at'], name='analytics_c_source__7f718d_idx'), models.Index(fields=['link_type', '-created_at'], name='analytics_c_link_ty_a3e0ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrendingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1d', models.FloatField(default=0.0)),
                ('score_7d', models.FloatField(default=0.0)),
                ('score_30d', models.FloatField(default=0.0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_score', to='catalog.app')),
            ],
            options={
                'indexes': [models.Index(fields=['-score_7d'], name='analytics_t_score_7_adcbee_idx'), models.Index(fields=['-score_1d'], name='analytics_t_score_1_c16915_idx'), models.Index(fields=['-score_30d'], name='analytics_t_score_3_d6601c_idx')],
            },
        ),
    ]
