# Generated by Django 5.2.14 on 2026-05-12 15:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=280)),
                ('long_description', models.TextField(blank=True)),
                ('verdict', models.CharField(blank=True, max_length=280)),
                ('developer_name', models.CharField(blank=True, max_length=200)),
                ('developer_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='apps/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='apps/covers/')),
                ('official_page_url', models.URLField(blank=True)),
                ('install_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden by editor')], default='draft', max_length=20)),
                ('platform_verification_status', models.CharField(choices=[('official', 'Listed in official platform directory'), ('not_listed', 'Not listed in any platform directory'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('editorial_review_status', models.CharField(choices=[('reviewed', 'Reviewed by editor'), ('unreviewed', 'Not yet reviewed')], default='unreviewed', max_length=20)),
                ('developer_claim_status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('pending', 'Claim pending'), ('claimed', 'Verified by developer')], default='unclaimed', max_length=20)),
                ('launch_status', models.CharField(choices=[('live', 'Live'), ('beta', 'Beta'), ('waitlist', 'Waitlist'), ('deprecated', 'Deprecated')], default='live', max_length=20)),
                ('pricing_model', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('freemium', 'Freemium'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_indexable', models.BooleanField(default=True)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('search_index_text', models.TextField(blank=True, default='')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-quality_score', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('public_path', models.CharField(help_text="URL segment used in platform pages and sitemap (e.g. 'chatgpt-apps', 'claude-connectors', 'mcp-servers').", max_length=80, unique=True)),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AppCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.app')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.capability')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='apps', through='catalog.AppCapability', to='catalog.capability'),
        ),
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.app')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='apps', through='catalog.AppCategory', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='app',
            name='listing_types',
            field=models.ManyToManyField(blank=True, related_name='apps', to='catalog.listingtype'),
        ),
        migrations.CreateModel(
            name='AppPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_status', models.CharField(choices=[('supported', 'Supported'), ('partial', 'Partial'), ('preview', 'Preview'), ('unknown', 'Unknown')], default='supported', max_length=20)),
                ('supported_plans', models.JSONField(blank=True, default=list)),
                ('region_availability', models.CharField(choices=[('worldwide', 'Worldwide'), ('us_only', 'US only'), ('eu_only', 'EU only'), ('excludes_eea', 'Excludes EEA'), ('limited', 'Limited (see notes)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('supported_models', models.CharField(blank=True, help_text='Free text. Models the listing works with.', max_length=300)),
                ('scope_summary', models.CharField(blank=True, help_text='Human summary of the permissions the integration requests.', max_length=280)),
                ('official_directory_url', models.URLField(blank=True)),
                ('install_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('last_verified_on_platform_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to='catalog.app')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_links', to='catalog.platform')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='apps', through='catalog.AppPlatform', to='catalog.platform'),
        ),
        migrations.CreateModel(
            name='AppUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.app')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usecase')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='use_cases',
            field=models.ManyToManyField(blank=True, related_name='apps', through='catalog.AppUseCase', to='catalog.usecase'),
        ),
        migrations.AddIndex(
            model_name='appcapability',
            index=models.Index(fields=['capability', 'value'], name='catalog_app_capabil_90330b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appcapability',
            unique_together={('app', 'capability')},
        ),
        migrations.AddIndex(
            model_name='appcategory',
            index=models.Index(fields=['category', 'app'], name='catalog_app_categor_823bbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appcategory',
            unique_together={('app', 'category')},
        ),
        migrations.AddIndex(
            model_name='appplatform',
            index=models.Index(fields=['platform', 'app'], name='catalog_app_platfor_c547d1_idx'),
        ),
        migrations.AddIndex(
            model_name='appplatform',
            index=models.Index(fields=['region_availability'], name='catalog_app_region__5203eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appplatform',
            unique_together={('app', 'platform')},
        ),
        migrations.AlterUniqueTogether(
            name='appusecase',
            unique_together={('app', 'use_case')},
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['status', '-quality_score'], name='catalog_app_status_188a52_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['-first_seen_at'], name='catalog_app_first_s_dd6649_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['is_featured', '-quality_score'], name='catalog_app_is_feat_0d5c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='app_search_vector_gin'),
        ),
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='app_name_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='app',
            index=django.contrib.postgres.indexes.GinIndex(fields=['developer_name'], name='app_dev_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.CheckConstraint(condition=models.Q(('quality_score__gte', 0), ('quality_score__lte', 100)), name='app_quality_score_range'),
        ),
    ]
